name: Welcome Message
on:
  issues:
    types: [opened]
jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: Comment
      uses: actions/github-script@v5
      with:
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: 'Witaj w projekcie! Dziękujemy za Twoją aktywność!'
          })


